// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrpheailknubabyvsggy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycGhlYWlsa251YmFieXZzZ2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTg1MTEsImV4cCI6MjA1ODg3NDUxMX0.VerGnAV2zq_rjyxWMv0BCwmjwjYPv12Qu76J4a8lm6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);